using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ITI.HistoryTreasures
{
    public enum CharacterEnum
    {
        MCFACE, MCFACERIGHT, MCFACELEFT, MCBACK, MCBACKRIGHT, MCBACKLEFT, MCLEFT, MCLEFTRIGHT, MCLEFTLEFT, MCRIGHT, MCRIGHTRIGHT, MCRIGHTLEFT,
        PNJGIRL, PNJGIRLRIGHT, PNJGIRLLEFT,PNJGIRLBACK, PNJCREED, PNJCREEDRIGHT, PNJCREEDLEFT,PNJCREEDBACK, PNJUNDERTAKER, PNJUNDERTAKERRIGHT, PNJUNDERTAKERLEFT,PNJUNDERTAKERBACK, PNJGUARD, PNJGUARDRIGHT, PNJGUARDLEFT,PNJGUARDBACK
    }
}
